epoch: 10

LearningRate:
  base_lr: 0.0001
  schedulers:
    - !YOLOv5LRDecay
      max_epochs: 10
      min_lr_ratio: 1
    - name: LinearWarmup
      start_factor: 0.
      epochs: 1

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
