epoch: 100

LearningRate:
  base_lr: 0.001
  schedulers:
  - !YOLOv5LRDecay
    max_epochs: 100
    min_lr_ratio: 0.1
  - !ExpWarmup
    epochs: 1

OptimizerBuilder:
  optimizer:
    type: Momentum
    momentum: 0.937
    use_nesterov: True
  regularizer:
    factor: 0.0005
    type: L2
  clip_grad_by_norm: 10.