_BASE_: [
  'gdgrid_detection.yml',
  '../PaddleYOLO/configs/runtime.yml',
  'optimizer_ppyoloe_10e.yml',
  '../PaddleYOLO/configs/ppyoloe/_base_/ppyoloe_plus_crn.yml',
  '../PaddleYOLO/configs/ppyoloe/_base_/ppyoloe_plus_reader.yml',
]

log_iter: 100
snapshot_epoch: 5
weights: output/ppyoloe_plus_crn_s_80e_coco/model_final

pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_s_obj365_pretrained.pdparams
depth_mult: 0.33
width_mult: 0.50
TrainReader:
  batch_size: 16