_BASE_: [
  'gdgrid_detection.yml',
  '../PaddleYOLO/configs/runtime.yml',
  'optimizer_100e.yml',
  '../PaddleYOLO/configs/yolov10/_base_/yolov10_cspdarknet.yml',
  '../PaddleYOLO/configs/yolov10/_base_/yolov10_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 50
snapshot_epoch: 10
weights: output/yolov10_s_500e_coco/model_final

YOLOv10CSPDarkNet:
  last_stage_ch: 1024
  use_c2fcib: true
  use_large_kernel: true

YOLOv10CSPPAN:
  fpn_use_c2fcib: [false, false]
  pan_use_c2fcib: [false, true]
  use_large_kernel: true

TrainReader:
  batch_size: 16
