_BASE_: [
  'dataset.yml',
  '../PaddleYOLO/configs/runtime.yml',
  'optimizer_100e.yml',
  '../PaddleYOLO/configs/yolov5/_base_/yolov5_cspdarknet.yml',
  '../PaddleYOLO/configs/yolov5/_base_/yolov5_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 10
weights: output/yolov5_s_300e_coco/model_final


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128
